name: Deploy to Firebase

on:
  push:
    branches:
      - main
  workflow_dispatch: # Allow manual trigger

env:
  NODE_VERSION: '22'

jobs:
  deploy:
    name: Deploy Firebase Functions
    runs-on: ubuntu-latest
    
    # Grant GITHUB_TOKEN write permissions for id-token
    permissions:
      contents: read
      id-token: write
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: latest

      - name: Get pnpm store directory
        id: pnpm-store
        shell: bash
        run: |
          STORE_PATH=$(cd functions && pnpm store path --silent)
          echo "STORE_PATH=$STORE_PATH" >> $GITHUB_ENV
          echo "path=$STORE_PATH" >> $GITHUB_OUTPUT

      - name: Setup pnpm cache
        uses: actions/cache@v4
        with:
          path: ${{ steps.pnpm-store.outputs.path }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('functions/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies (including dev)
        working-directory: ./functions
        run: |
          pnpm install --frozen-lockfile

      - name: Lint code
        working-directory: ./functions
        run: |
          pnpm run lint

      - name: Build project
        working-directory: ./functions
        run: |
          pnpm run build

      - name: Authenticate to Google Cloud
        id: auth
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: projects/463220462105/locations/global/workloadIdentityPools/github-pool/providers/github
          service_account: firebase-adminsdk-fbsvc@mikita-dev-f86aa.iam.gserviceaccount.com

      - name: Install Firebase CLI
        run: |
          npm install -g firebase-tools

      - name: Deploy to Firebase Functions
        run: |
          firebase deploy --only functions
