name: Deploy to Firebase

on:
  push:
    branches:
      - main
  workflow_dispatch: # Allow manual trigger

env:
  NODE_VERSION: '22'

jobs:
  build-and-deploy:
    name: Deploy Firebase Functions
    runs-on: ubuntu-latest
    
    # Grant GITHUB_TOKEN write permissions for id-token
    permissions:
      contents: read
      id-token: write
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup and Build
        uses: ./.github/actions/setup-and-build

      - name: Authenticate to Google Cloud
        id: auth
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: projects/463220462105/locations/global/workloadIdentityPools/github-pool/providers/github
          service_account: firebase-adminsdk-fbsvc@mikita-dev-f86aa.iam.gserviceaccount.com

      - name: Install Firebase CLI
        run: |
          npm install -g firebase-tools

      - name: Deploy to Firebase Functions
        run: |
          firebase deploy --only functions
